# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2025-02-19 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='html_content',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='newsletter',
            old_name='scheduled_time',
            new_name='send_at',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='subscribers',
            field=models.ManyToManyField(to='mailing.Subscriber'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
