# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2025-02-20 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_newsletter_html_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailClick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('link_url', models.URLField()),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.Newsletter')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.Subscriber')),
            ],
        ),
        migrations.CreateModel(
            name='EmailOpen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.Newsletter')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.Subscriber')),
            ],
        ),
    ]
